# Generated by Django 5.0.2 on 2024-03-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
